### ISSUE TITLE
NullPointerException when performing Stack analysis

### ISSUE THREAD

**Issue by LRFLEW** [pedro-javierf/NTRGhidra#7]
**Describe the bug**
I was using this extension to disassemble Rhythm Heaven (YLZE01). When running the auto analysis when first opening the imported ARM9 ROM, a NullPointerException gets thrown during the stack analysis. Re-running the stack analysis continues to result in NullPointerExceptions. The stack trace I was able to get doesn't include any of this project's code, but it might still be a bug with this if the main issue is in the import process.

**To Reproduce**
1. Add the Rhythm Heaven ROM to Ghidra
2. On the NTRGhidra dialogs, select ARM9, then Yes.
3. Once imported, open the project, select Yes on the auto-analyze prompt, ensure Stack is selected, and click Analyze
4. Wait for it to get to the Stack analysis.

**Expected behavior**
Not to result in a NullPointerException

**Stack Trace**
```
Cannot invoke "ghidra.program.model.address.Address.getAddressSpace()" because "this.address" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.address.Address.getAddressSpace()" because "this.address" is null
	at ghidra.program.model.pcode.Varnode.<init>(Varnode.java:52)
	at ghidra.program.util.VarnodeContext.getVarnode(VarnodeContext.java:871)
	at ghidra.program.util.SymbolicPropogator.applyPcode(SymbolicPropogator.java:837)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:495)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:393)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:191)
	at ghidra.app.cmd.function.NewFunctionStackAnalysisCmd.createStackPointerVariables(NewFunctionStackAnalysisCmd.java:340)
	at ghidra.app.cmd.function.NewFunctionStackAnalysisCmd.analyzeFunction(NewFunctionStackAnalysisCmd.java:191)
	at ghidra.app.cmd.function.NewFunctionStackAnalysisCmd.applyTo(NewFunctionStackAnalysisCmd.java:118)
	at ghidra.app.plugin.core.function.StackVariableAnalyzer.added(StackVariableAnalyzer.java:55)
	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:47)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

---------------------------------------------------
Build Date: 2020-Nov-13 1112 EST
Ghidra Version: 9.2
Java Home: C:\Users\LRFLEW\Downloads\jdk-15.0.2
JVM Version: Oracle Corporation 15.0.2
OS: Windows 10 10.0 amd64

**My System:**
 - OS: Windows 10 20H2
 - hidra 9.2
 - NTRGhidra 1.4.3

**Comment by pedro-javierf** [comment]
This is a sightly inconvenient problem, I believe the cause of the error is that Ghidra doesn't find a .stack region. That's because the loader doesn't create it for the following reason: the stack location is set dynamically, and it depends on the ctr0 (the code that initializes the system and the CPU). This code varies from one SDK version to another, and so does the stack location. It also depends on the IRQ stack region which was configurable by the developers and affects the main stack as well.

Homebrew, on the other side, uses a completely different initialization code, so it's going to be another scenario to cover.

A possible enhancement would be to dynamically read the first 20-30 instructions of the disassembled program (from the entry point) and figure the final value of the SP (Stack Pointer) after the IRQ stack is set, then create a Ghidra memory region at that address.

**That being said**, it is usually fine to run the analysis **without** the _stack_ option.

**Comment by LRFLEW** [comment]
> I believe the cause of the error is that Ghidra doesn't find a .stack region

This doesn't sound right to me, personally. I don't remember seeing a stack memory region when working with PE (EXE) files. Also, if the error was a missing stack memory region, I would have expected the error to occur immidiately, not when the progress bar gets half way.

If you think this is the issue, then we can test it. If we make a build that creates a .stack region in a hardcoded location for the game I was having issues with, I can see if the error still occurs with the patch. If it doesn't fix the issue, then we don't need to consider the enhancement as a method to fix the issue.

**Comment by pedro-javierf** [comment]
After more testing I have to discard that hypothesis. I have been able to reproduce the error; It seems the loader is failing with the same exception on games which worked and were analysed perfectly previously. It must be a bug either introduced in the last version or caused by the changes in the Ghidra codebase, which usually breaks things. Needs more investigation

**Comment by pedro-javierf** [comment]
@LRFLEW can you test if the error persist with the [latest release v1.4.4.0](https://github.com/pedro-javierf/NTRGhidra/releases/tag/v1.4.4.0) ?

**Comment by LRFLEW** [comment]
I was able to get the NullPointerException again with the latest release. Looking at that stack trace, it seems less like one long stack trace and instead is multiple identical stack traces printed. If that is the case, it would  suggest that the failures don't prevent the rest of the stack analysis from being performed, which is good. I don't know the codebase (yours or Ghidra's) to know what the stack trace means, but the fact that it seems to **end** with `Caused by: java.lang.NullPointerException` has me worried this isn't a complete trace.

**Comment by astrelsky** [comment]
The trace for the Decompiler Switch Analyzer definitely isn't a complete trace. It might get logged if you set the logging configuration to trace, but it might not. (See conversation [here](https://github.com/NationalSecurityAgency/ghidra/issues/1252)).

Does the initial problem occur with the `USE_NEW_FUNCTION_STACK_ANALYSIS` option set to false as well?

I'm baffled by this as it appears that the initial stack trace should be impossible. I opened up [#2787](https://github.com/NationalSecurityAgency/ghidra/issues/2787) and mentioned this issue since `VarnodeContext` is passing a null `Address` to the `Varnode` contructor when it cannot be null.

In the jython terminal try the following when the cursor is on a valid instruction.
```python
spaceID = getInstructionAt(currentAddress).getAddressSpace().getSpaceID();
addrFactory = new OffsetAddressFactory(currentProgram.getLanguage().getAddressFactory());
space = addrFactory.getAddressSpace(spaceID)
```
Check if space is `None`

**Comment by pedro-javierf** [comment]
> The trace for the Decompiler Switch Analyzer definitely isn't a complete trace. It might get logged if you set the logging configuration to trace, but it might not. (See conversation [here](https://github.com/NationalSecurityAgency/ghidra/issues/1252)).
> 
> Does the initial problem occur with the `USE_NEW_FUNCTION_STACK_ANALYSIS` option set to false as well?
> 
> I'm baffled by this as it appears that the initial stack trace should be impossible. I opened up [#2787](https://github.com/NationalSecurityAgency/ghidra/issues/2787) and mentioned this issue since `VarnodeContext` is passing a null `Address` to the `Varnode` contructor when it cannot be null. I also referenced [#2785](https://github.com/NationalSecurityAgency/ghidra/issues/2785) that you created earlier.
> 
> In the jython terminal try the following when the cursor is on a valid instruction.
> 
> ```python
> spaceID = getInstructionAt(currentAddress).getAddressSpace().getSpaceID();
> addrFactory = new OffsetAddressFactory(currentProgram.getLanguage().getAddressFactory());
> space = addrFactory.getAddressSpace(spaceID)
> ```
> 
> Check if space is `None`



Where can I set the logging configuration to trace everything? Additionally, where do I need to set to false the USE_NEW_FUNCTION_STACK_ANALYSIS? Is that the same option as "Stack" Analysis on the GUI?

Regarding the python script, It seems getAddressSpace() in InstructionDB [does not exist:](https://ghidra.re/ghidra_docs/api/ghidra/program/database/code/InstructionDB.html)
![image](https://user-images.githubusercontent.com/12979814/108623668-797e9580-7440-11eb-9364-34763e3fd71e.png)

**Comment by astrelsky** [comment]
My mistake, it should have been `getInstructionAt(currentAddress).getMinAddress()...`. It is a bit redundant to do that since you have the address already but it is for consistency with what is going on during the problem.

The option is the same in the gui. It is to use the "new" stack analysis or something.

**Comment by pedro-javierf** [comment]
> My mistake, it should have been `getInstructionAt(currentAddress).getMinAddress()...`. It is a bit redundant to do that since you have the address already but it is for consistency with what is going on during the problem.
> 
> The option is the same in the gui. It is to use the "new" stack analysis or something.
> 
> Regarding the log configuration: [NationalSecurityAgency/ghidra#1252 (comment)](https://github.com/NationalSecurityAgency/ghidra/issues/1252#issuecomment-555129549)

Okay, I've fixed the jython script to run (Let me know if this is what you meant to execute):

```python
spaceID = getInstructionAt(currentAddress).getMinAddress().getAddressSpace().getSpaceID()
addrFactory = currentProgram.getLanguage().getAddressFactory();
space = addrFactory.getAddressSpace(spaceID)
```

And the content of space is not None but rather:


```
>>> space
ram:
```

Additionally, running analysis without the stack option like this:
![image](https://user-images.githubusercontent.com/12979814/108626959-3f6abf00-7453-11eb-8888-5bef515653d4.png)

Produces different output. The previous NullPointerException exception does not appear but the other underlying and repeating exceptions keep appearing:

![image](https://user-images.githubusercontent.com/12979814/108627063-eea79600-7453-11eb-86a3-865affbc0e0d.png)


I'm still figuring how to get the actual trace, just modifying the entries in /support/debug.log4j.xml did not work (or I'm not looking in the correct place)

**Comment by pedro-javierf** [comment]
The issue was solved with https://github.com/NationalSecurityAgency/ghidra/issues/2787 and the next NTRGhidra release will have this issue solved
